#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block compile gitsubmodule
  chmod 755 "$shome/vendor/nvm/nvm.sh"
  ln -vnfs "$shome/vendor/nvm" "${BOARD_PATH}/.nvm"
}

main "$@"
