#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  git clone -b "v${NVM_VERSION}" git@github.com:creationix/nvm "$shome/vendor/nvm-${NVM_VERSION}" || true
  rm -rf "$shome/vendor/nvm"
  ln -nfs "nvm-${NVM_VERSION}" "$shome/vendor/nvm"
}

main "$@"
