#!/usr/bin/env bash

function _nvm_profile {
  local shome="${_nvm_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin::$PATH"


  export NVM_DIR="$shome/vendor/nvm"
}

_nvm_profile
